# SPDX-FileCopyrightText: 2020 Benedict Harcourt
#
# SPDX-License-Identifier: BSD-2-Clause

name: SPDX Lint

on:
  push:
    branches:
      - mainline
  pull_request:

jobs:
  spdx-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1.1
